// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/i18n/en.ts
var en_default = {
  nav: {
    home: "Home",
    services: "Services",
    team: "Team",
    cases: "Clinical Cases",
    reviews: "Reviews",
    contacts: "Contacts",
    book: "Book"
  },
  hero: {
    title: "Your Smile is Our Mission",
    subtitle: "Since 1970, a point of reference in the center of Milan for a beautiful, healthy and lasting smile",
    bookVisit: "Book a Visit",
    discoverServices: "Discover Services"
  },
  services: {
    title: "Our Services",
    subtitle: "We offer a full range of dental treatments with the most advanced technologies",
    hygiene: "Hygiene & Prevention",
    hygieneDesc: "Professional cleaning, scaling and periodic check-ups to keep your teeth healthy.",
    orthodontics: "Orthodontics",
    orthodonticsDesc: "Fixed, removable and invisible braces for a perfectly aligned smile.",
    aesthetics: "Aesthetics",
    aestheticsDesc: "Whitening, veneers and face contouring with fillers for a bright smile and a youthful face.",
    conservative: "Restorative Dentistry",
    conservativeDesc: "Cavity treatment with state-of-the-art materials and minimally invasive techniques.",
    implantology: "Implantology",
    implantologyDesc: "Dental implants with digital technology to replace missing teeth.",
    periodontics: "Periodontics",
    periodonticsDesc: "Prevention and treatment of gum diseases for healthy and strong gums.",
    prosthetics: "Prosthetics",
    prostheticsDesc: "Custom-made artificial devices that replace missing or compromised teeth.",
    endodontics: "Endodontics",
    endodonticsDesc: "Root canal treatments to save compromised teeth and relieve pain.",
    pedodontics: "Pedodontics",
    pedodonticsDesc: "Dental care for children in a calm and welcoming environment."
  },
  team: {
    title: "Our Team",
    subtitle: "Professionals dedicated to your well-being and the health of your smile",
    paolo: "Dr. Paolo Maria Brotto",
    paoloRole: "Medical Director",
    paoloDesc: "Graduated in Medicine and Surgery and specialized in odontostomatology at the University of Milan. Master's in Orthodontics at Boston University. Master's in Periodontology at Galeazzi Hospital in Milan. Medical director of the practice since 1993, expert in implantology, prosthetics, endodontics, restorative dentistry, surgery and orthodontics for adults and children.",
    valentina: "Valentina Del Giudice",
    valentinaRole: "Dental Assistant",
    valentinaDesc: "Specialized in treatment assistance and patient care.",
    elena: "Elena Poggi",
    elenaRole: "Secretary",
    elenaDesc: "The reference point for appointments and administrative management of the practice."
  },
  cases: {
    title: "Resolved Clinical Cases",
    subtitle: "Excellent results that testify to the quality of our work",
    implantology: "Implantology",
    implantologyDesc: "Complete restoration of dental arches with state-of-the-art implants to restore function and aesthetics.",
    prosthetics: "Prosthetics",
    prostheticsDesc: "Custom prosthetic rehabilitations to replace missing or compromised teeth with natural-looking results.",
    orthodontics: "Orthodontics",
    orthodonticsDesc: "Correction of malocclusions and dental misalignments for a harmonious and functional smile.",
    beforeAfter: " "
  },
  reviews: {
    title: "Google Reviews",
    subtitle: "Read the opinions of our patients on Google",
    averageRating: "Average rating on Google",
    readReviews: "Read Google Reviews",
    leaveReview: "Leave a Review",
    reviewCTA: "Your opinion matters! Google reviews help other patients learn about the quality of our service.",
    averageFooter: "Average rating:",
    onGoogle: "on Google"
  },
  contact: {
    title: "Contacts & Hours",
    subtitle: "We are here for you. Contact us to book your visit",
    contactInfo: "Contact Information",
    address: "Address",
    phone: "Phone",
    fax: "Phone",
    phone2: "Phone",
    email: "Email",
    bookNow: "Book Now",
    openingHours: "Opening Hours",
    days: "Monday to Thursday",
    morning: "Morning:",
    afternoon: "Afternoon:",
    byAppointment: "By appointment only",
    howToReach: "How to Reach Us",
    tram: "Tram",
    tramDesc: "130 m from tram stop No.: 2 \u2013 3 \u2013 14 \u2013 20 \u2013 24 \u2013 27",
    bus: "Bus",
    busDesc: "180 m from bus stop No. 50",
    metro: "Metro",
    metroMissori: "180 m from MISSORI station, YELLOW line",
    metroDuomo: "220 m from DUOMO station, RED line",
    metroCordusio: "~400 m from CORDUSIO station, RED line"
  },
  about: {
    back: "Back to Home",
    name: "Dr. Pietro Paolo Maria Brotto",
    subtitle: "Medical Director \u2013 Brotto Dental Practice",
    bioTitle: "Biography",
    bio1: "Born in Milan on January 23, 1960.",
    bio2: "Degree in Medicine and Surgery from the University of Milan in 1986.",
    bio3: "Service as Auxiliary Carabiniere in the infirmary at the Lamarmora barracks in Milan.",
    bio4: "Specialization in Odontostomatology at the same University in 1989.",
    bio5: "Master's in Orthodontics in Boston \u2013 Massachusetts (USA), 1989/1992.",
    bio6: "Master's in Periodontology at Galeazzi Hospital in Milan, 2001-2003.",
    languagesTitle: "Languages",
    languages: "Native English speaker, Spanish and French.",
    familyTitle: "Family",
    family: "Married for 35 years, father of 5 children.",
    experienceTitle: "Professional Experience",
    exp1: "Specializes in restorative dentistry, prevention, orthodontics for children and adults, implantology and surgery, dental prosthetics.",
    exp2: "Former CTU (Court-Appointed Technical Consultant) at the Court of Milan.",
    exp3: "Active member of ANDI, OMCEO, AAO, SIDP, BUIA, ASIO.",
    certTitle: "Philosophy & Certifications",
    cert: "Highest quality standards backed by UNI EN ISO 9001:2015 Certification, held since 2005.",
    studioTitle: "Practice History",
    studio1: "Brotto Dental Practice was founded in 1970 by Dr. Luigi Brotto in central Milan.",
    studio2: "A point of reference in central Milan for over 50 years."
  },
  footer: {
    description: "Since 1970, a point of reference in the center of Milan for the health and beauty of your smile. ISO 9001:2015 certified.",
    contacts: "Contacts",
    hours: "Hours",
    days: "Monday to Thursday",
    byAppointment: "By appointment only",
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    privacyLink: "Privacy"
  },
  privacy: {
    title: "Privacy Policy",
    subtitle: "Information on the processing of personal data",
    back: "Back to Home",
    owner: {
      title: "Data Controller",
      name: "Brotto Studio Odontoiatrico (individual practice)",
      address: "Via Unione 2, 20122 Milan, Italy \u2013 VAT 05377030969",
      email: "Email: info@brottostudio.it",
      phone: "Phone: 02 86462283"
    },
    data: {
      title: "Personal data collected",
      content: "We collect personal data that you provide directly when you contact us by phone or email to make an appointment or request information (e.g., name, surname, phone number, email address).\n\nWhen you visit the site, we may automatically collect browsing data such as IP address, browser type, operating system, and pages visited, through the technical services used to display maps and reviews."
    },
    purpose: {
      title: "Purpose of processing",
      content: "Data is processed for the following purposes:\n\n\u2022 responding to information and booking requests;\n\u2022 managing appointments and patient relationships;\n\u2022 fulfilling legal, accounting, and tax obligations;\n\u2022 ensuring the security and proper functioning of the site."
    },
    legal: {
      title: "Legal basis and retention",
      content: "The processing of personal data is based on the performance of pre-contractual measures at the request of the data subject, compliance with legal obligations, and the legitimate interest of the controller in managing the practice.\n\nData is retained for the time necessary for the stated purposes and in any case within the terms provided by applicable law. Health data is processed in accordance with the rules applicable to special categories of personal data."
    },
    cookies: {
      title: "Cookies and similar technologies",
      content: "This site uses only technical cookies necessary for the operation of the site and for storing the user's selected language. We do not use profiling cookies or analytics/tracking tools.\n\nIf analytics or marketing services are added in the future, a cookie consent banner will be displayed to manage consent."
    },
    thirdParties: {
      title: "Third-party services",
      content: "The site uses the following third-party services:\n\n\u2022 Google Maps / Google Reviews: to display the location of the practice and reviews. These services may use cookies or tracking technologies according to their own policies. We invite you to consult Google's privacy policy.\n\n\u2022 Website hosting: browsing data passes through the servers of the hosting platform used for the site."
    },
    rights: {
      title: "Data subject rights",
      content: "You have the right to:\n\n\u2022 access your personal data;\n\u2022 request rectification or erasure;\n\u2022 request restriction of processing;\n\u2022 object to processing;\n\u2022 request data portability.\n\nTo exercise your rights, you can write to info@brottostudio.it. You also have the right to lodge a complaint with the Italian Data Protection Authority (Garante per la protezione dei dati personali)."
    },
    changes: {
      title: "Changes to this policy",
      content: "This policy may be updated in case of regulatory or organizational changes. We invite you to check this page periodically."
    }
  }
};

// src/lib/mcp/tools/get-services.ts
var get_services_default = defineTool({
  name: "get_services",
  title: "Get dental services",
  description: "List all dental services offered by Brotto Dental Practice with a short description for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const s = en_default.services;
    const services = [
      { key: "hygiene", name: s.hygiene, description: s.hygieneDesc },
      { key: "orthodontics", name: s.orthodontics, description: s.orthodonticsDesc },
      { key: "aesthetics", name: s.aesthetics, description: s.aestheticsDesc },
      { key: "conservative", name: s.conservative, description: s.conservativeDesc },
      { key: "implantology", name: s.implantology, description: s.implantologyDesc },
      { key: "periodontics", name: s.periodontics, description: s.periodonticsDesc },
      { key: "prosthetics", name: s.prosthetics, description: s.prostheticsDesc },
      { key: "endodontics", name: s.endodontics, description: s.endodonticsDesc },
      { key: "pedodontics", name: s.pedodontics, description: s.pedodonticsDesc }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/get-team.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_team_default = defineTool2({
  name: "get_team",
  title: "Get dental team",
  description: "List the professionals at Brotto Dental Practice with role and short biography.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const t = en_default.team;
    const team = [
      { name: t.paolo, role: t.paoloRole, bio: t.paoloDesc },
      { name: t.valentina, role: t.valentinaRole, bio: t.valentinaDesc },
      { name: t.elena, role: t.elenaRole, bio: t.elenaDesc }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(team, null, 2) }],
      structuredContent: { team }
    };
  }
});

// src/lib/mcp/tools/get-clinical-cases.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_clinical_cases_default = defineTool3({
  name: "get_clinical_cases",
  title: "Get clinical case areas",
  description: "List the macro-areas of resolved clinical cases (implantology, prosthetics, orthodontics) with descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const c = en_default.cases;
    const cases = [
      { area: c.implantology, description: c.implantologyDesc },
      { area: c.prosthetics, description: c.prostheticsDesc },
      { area: c.orthodontics, description: c.orthodonticsDesc }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(cases, null, 2) }],
      structuredContent: { cases }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact information",
  description: "Get the address, phone, email, opening hours, and public transport directions for Brotto Dental Practice in Milan.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const c = en_default.contact;
    const info = {
      hours: {
        days: c.days,
        note: c.byAppointment
      },
      howToReach: {
        tram: c.tramDesc,
        bus: c.busDesc,
        metro: [c.metroMissori, c.metroDuomo, c.metroCordusio]
      },
      website: "See the site for full address, phone number and email."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-practice-info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_practice_info_default = defineTool5({
  name: "get_practice_info",
  title: "Get practice information",
  description: "Get an overview of Brotto Dental Practice: history, philosophy, certifications, and director biography.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const a = en_default.about;
    const info = {
      name: "Brotto Dental Practice",
      tagline: en_default.hero.subtitle,
      director: {
        name: a.name,
        role: a.subtitle,
        biography: [a.bio1, a.bio2, a.bio3, a.bio4, a.bio5, a.bio6],
        languages: a.languages,
        experience: [a.exp1, a.exp2, a.exp3]
      },
      philosophy: a.cert,
      history: [a.studio1, a.studio2]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "brotto-dental-mcp",
  title: "Brotto Dental Practice",
  version: "0.1.0",
  instructions: "Public information about Brotto Dental Practice in Milan. Use these tools to answer questions about services, the team, resolved clinical cases, contact information, opening hours, directions, and the practice's history and philosophy.",
  tools: [get_services_default, get_team_default, get_clinical_cases_default, get_contact_info_default, get_practice_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
